# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d30f5472483ae79d5cc2eb7f45673cee4bf077b45e2ebb44a908b06473f4d370c14dd2b292c6b0b33c151a4ef39bc47a7b0c6c2014c8d473fa7a0324ce2cefe3

test:
  secret_key_base: 579aee465a29b7fd48ed41e8865708975678641bf8eb22d51269542fb92e06505886528b63082376498fd83c006a072a3ed74c42a107520fb27901fe252a807e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
